"""
UE5 Lighting Applier

Reads a JSON lighting configuration (generated by analyze_lighting.py) and
applies it to the current Unreal Engine scene via the unreal Python API.

Usage (inside UE5 Python console):
    exec(open('/path/to/ue_lighting_applier.py').read())

Or import as module:
    from ue_lighting_applier import apply_lighting_config
    apply_lighting_config("lighting_config.json")
"""

import json
import sys
from pathlib import Path

try:
    import unreal
except ImportError:
    unreal = None
    print("Warning: 'unreal' module not available. Running in preview/dry-run mode.")


def _find_or_spawn_actor(actor_class, label: str):
    """Find an existing actor by class or spawn a new one."""
    subsystem = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)

    # Search existing actors
    actors = unreal.EditorFilterLibrary.by_class(
        subsystem.get_all_level_actors(), actor_class
    )
    if actors:
        return actors[0]

    # Spawn new actor at origin
    actor = subsystem.spawn_actor_from_class(actor_class, unreal.Vector(0, 0, 0))
    actor.set_actor_label(label)
    return actor


def apply_directional_light(config: dict):
    """Apply directional light (sun) settings."""
    if not config:
        return

    light = _find_or_spawn_actor(unreal.DirectionalLight, "AI_Sun")
    component = light.get_component_by_class(unreal.DirectionalLightComponent)

    if "rotation_pitch" in config or "rotation_yaw" in config:
        rotation = light.get_actor_rotation()
        if "rotation_pitch" in config:
            rotation.pitch = config["rotation_pitch"]
        if "rotation_yaw" in config:
            rotation.yaw = config["rotation_yaw"]
        light.set_actor_rotation(rotation, False)

    if "intensity_lux" in config:
        component.set_editor_property("intensity", config["intensity_lux"])
        component.set_editor_property("intensity_units", unreal.LightUnits.LUX)

    if "color_temperature_kelvin" in config:
        component.set_editor_property("use_temperature", True)
        component.set_editor_property("temperature", config["color_temperature_kelvin"])

    if "light_source_angle" in config:
        component.set_editor_property("light_source_angle", config["light_source_angle"])

    print(f"  Directional light applied: {config.get('intensity_lux', '?')} lux, "
          f"{config.get('color_temperature_kelvin', '?')}K")


def apply_sky_atmosphere(config: dict):
    """Apply sky atmosphere settings."""
    if not config:
        return

    sky = _find_or_spawn_actor(unreal.SkyAtmosphere, "AI_SkyAtmosphere")
    component = sky.get_component_by_class(unreal.SkyAtmosphereComponent)

    if "rayleigh_scattering_scale" in config:
        component.set_editor_property("rayleigh_scattering_scale", config["rayleigh_scattering_scale"])

    if "mie_scattering_scale" in config:
        component.set_editor_property("mie_scattering_scale", config["mie_scattering_scale"])

    if "absorption_scale" in config:
        component.set_editor_property("absorption_scale", config["absorption_scale"])

    print("  Sky atmosphere applied")


def apply_sky_light(config: dict):
    """Apply sky light (ambient) settings."""
    if not config:
        return

    light = _find_or_spawn_actor(unreal.SkyLight, "AI_SkyLight")
    component = light.get_component_by_class(unreal.SkyLightComponent)

    if "intensity_scale" in config:
        component.set_editor_property("intensity", config["intensity_scale"])

    if "tint" in config:
        r, g, b = config["tint"]
        component.set_editor_property("light_color", unreal.LinearColor(r, g, b, 1.0))

    # Recapture sky light after changes
    component.recapture_scene()
    print("  Sky light applied")


def apply_fog(config: dict):
    """Apply exponential height fog settings."""
    if not config or not config.get("enabled", False):
        return

    fog = _find_or_spawn_actor(unreal.ExponentialHeightFog, "AI_Fog")
    component = fog.get_component_by_class(unreal.ExponentialHeightFogComponent)

    if "fog_density" in config:
        component.set_editor_property("fog_density", config["fog_density"])

    if "fog_color" in config:
        r, g, b = config["fog_color"]
        component.set_editor_property("fog_inscattering_color", unreal.LinearColor(r, g, b, 1.0))

    if "fog_height_falloff" in config:
        component.set_editor_property("fog_height_falloff", config["fog_height_falloff"])

    if "start_distance" in config:
        component.set_editor_property("start_distance", config["start_distance"])

    if config.get("volumetric_fog", False):
        component.set_editor_property("volumetric_fog", True)

    print("  Fog applied")


def apply_post_process(config: dict):
    """Apply post-processing volume settings."""
    if not config:
        return

    pp = _find_or_spawn_actor(unreal.PostProcessVolume, "AI_PostProcess")
    pp.set_editor_property("unbound", True)  # Apply globally
    pp.set_editor_property("priority", 1.0)

    settings = pp.get_editor_property("settings")

    if "exposure_compensation" in config:
        settings.set_editor_property("override_auto_exposure_bias", True)
        settings.set_editor_property("auto_exposure_bias", config["exposure_compensation"])

    if "bloom_intensity" in config:
        settings.set_editor_property("override_bloom_intensity", True)
        settings.set_editor_property("bloom_intensity", config["bloom_intensity"])

    if "white_balance_temp" in config:
        settings.set_editor_property("override_white_temp", True)
        settings.set_editor_property("white_temp", config["white_balance_temp"])

    if "vignette_intensity" in config:
        settings.set_editor_property("override_vignette_intensity", True)
        settings.set_editor_property("vignette_intensity", config["vignette_intensity"])

    if "saturation" in config:
        settings.set_editor_property("override_color_saturation", True)
        sat = config["saturation"]
        settings.set_editor_property("color_saturation", unreal.Vector4(sat, sat, sat, sat))

    if "contrast" in config:
        settings.set_editor_property("override_color_contrast", True)
        con = config["contrast"]
        settings.set_editor_property("color_contrast", unreal.Vector4(con, con, con, con))

    print("  Post-processing applied")


def apply_lighting_config(config_path: str):
    """Load a lighting JSON config and apply all settings to the current UE scene."""
    path = Path(config_path)
    if not path.exists():
        print(f"Error: Config file not found: {path}")
        return

    with open(path) as f:
        config = json.load(f)

    mood = config.get("mood_metadata", {})
    print(f"\nApplying lighting: {mood.get('mood', 'unknown')} "
          f"({mood.get('time_of_day', '?')}, {mood.get('weather', '?')})")
    print(f"Description: {mood.get('description', 'N/A')}\n")

    with unreal.ScopedEditorTransaction("AI Lighting Apply") as trans:
        apply_directional_light(config.get("directional_light"))
        apply_sky_atmosphere(config.get("sky_atmosphere"))
        apply_sky_light(config.get("sky_light"))
        apply_fog(config.get("exponential_height_fog"))
        apply_post_process(config.get("post_process"))

    print("\nLighting applied successfully! Use Ctrl+Z to undo.")


# Default: look for lighting_config.json in same directory
if __name__ == "__main__" or unreal:
    _default_config = Path(__file__).parent / "lighting_config.json"
    if _default_config.exists():
        apply_lighting_config(str(_default_config))
    elif len(sys.argv) > 1:
        apply_lighting_config(sys.argv[1])
    else:
        print("Usage: provide a lighting_config.json path")
        print("  In UE Python: apply_lighting_config('/path/to/config.json')")
